CREATE USER IF NOT EXISTS 'appUser'@'localhost' IDENTIFIED WITH 'mysql_native_password' BY 'passWord';
GRANT ALL PRIVILEGES ON *.* TO 'appUser'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;

DROP DATABASE IF EXISTS trade_ticker;
CREATE DATABASE trade_ticker;
USE trade_ticker;

CREATE TABLE IF NOT EXISTS Users (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(255) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
